web:
  build: .
  dockerfile: Dockerfile.picoshell
  links:
    - db
  ports:
    - "127.0.0.1:3000:3000"

db:
  image: mysql:5.7
  ports:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: picodb