web:
  build: .
  dockerfile: Dockerfile.picoshell
  links:
    - db:mysql
  ports:
    - "127.0.0.1:3000:3000"

db:
  image: mysql:5.7
  # ports:
  #   - "127.0.0.1:3307:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: picodb